// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkKkrcyoSdBlRwgQ3ZXM1ZN8WwPnd9ZII',
    appId: '1:148039212465:web:e2d16aa2c8ee4cb361f190',
    messagingSenderId: '148039212465',
    projectId: 'test-app-ioniks',
    authDomain: 'test-app-ioniks.firebaseapp.com',
    storageBucket: 'test-app-ioniks.appspot.com',
    measurementId: 'G-KNQV97X2VB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDke1VjiYbhG-Sfe6NfFmQyZ2y6_f3QldU',
    appId: '1:148039212465:android:06921f0ff6aac5f261f190',
    messagingSenderId: '148039212465',
    projectId: 'test-app-ioniks',
    storageBucket: 'test-app-ioniks.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoYq43m1HztqljwpJ1_k1ShWWppHh74pQ',
    appId: '1:148039212465:ios:165f67b71a45309961f190',
    messagingSenderId: '148039212465',
    projectId: 'test-app-ioniks',
    storageBucket: 'test-app-ioniks.appspot.com',
    iosClientId: '148039212465-cbtmanp0t9jhnhvo1ju0cd595kp4mlue.apps.googleusercontent.com',
    iosBundleId: 'com.testing.testappfireBase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBoYq43m1HztqljwpJ1_k1ShWWppHh74pQ',
    appId: '1:148039212465:ios:76bb817d32e707ab61f190',
    messagingSenderId: '148039212465',
    projectId: 'test-app-ioniks',
    storageBucket: 'test-app-ioniks.appspot.com',
    iosClientId: '148039212465-0sm0iiubkkschudjdot51i87hh80r89s.apps.googleusercontent.com',
    iosBundleId: 'com.example.testapp',
  );
}
